services:
  helia:
    image: ipfs/kubo:latest
    container_name: helia-node
    ports: ['5001:5001','8080:8080']
    volumes: ['./data/helia:/data/ipfs']
    restart: unless-stopped

  hardhat:
    build:
      context: .
      dockerfile: ./hardhat/Dockerfile
    container_name: hardhat-node
    ports: ['8545:8545']
    volumes:
      - ./contracts:/app/contracts
      - ./scripts:/app/scripts
      - ./hardhat.config.cjs:/app/hardhat.config.cjs
      - ./test:/app/test
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: changeme
    ports: ['27017:27017']
    volumes: ['./data/mongo:/data/db']
    restart: unless-stopped

  minio:
    image: minio/minio:latest
    container_name: minio-server
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: localtest
      MINIO_ROOT_PASSWORD: localtest123
    ports: ['9000:9000','9001:9001']
    volumes: ['./data/minio:/data']
    restart: unless-stopped

  vault:
    image: hashicorp/vault:1.17.6
    container_name: vault-server
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: root
      VAULT_ADDR: http://0.0.0.0:8200
    ports: ['8200:8200']
    cap_add: [IPC_LOCK]
    restart: unless-stopped

  vault-init:
    image: hashicorp/vault:1.17.6
    container_name: vault-init
    depends_on:
      - vault
    volumes:
      - ./scripts/vault-init.sh:/usr/local/bin/vault-init.sh
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: root
    command: "sh /usr/local/bin/vault-init.sh"

  oracle-service:
    build:
      context: ./backend/oracle-service
      dockerfile: Dockerfile
    container_name: oracle-service
    env_file:
      - ./backend/oracle-service/.env
    dns:
      - 8.8.8.8
    ports: ['3000:3000']
    depends_on:
      - hardhat
      - mongo
      - risk-engine
    restart: unless-stopped

  risk-engine:
    build:
      context: ./cloud-training/cloud-training
      dockerfile: Dockerfile
    container_name: risk-engine
    environment:
      - PYTHONPATH=/app
    env_file:
      - ./cloud-training/.env
    ports: ['8001:8000']
    volumes:
      - ./cloud-training/cloud-training:/app
      - ./cloud-training/models:/app/models
    depends_on:
      - mongo
    restart: unless-stopped

networks:
  default:
    name: amttp-network
